// AUTO-GENERATED by scripts/split-locales.cjs — do not edit by hand.
import app from './en-US/app'
import dashboard from './en-US/dashboard'
import taskList from './en-US/taskList'
import taskDetail from './en-US/taskDetail'
import userGuide from './en-US/userGuide'
import clientGuide from './en-US/clientGuide'
import workerGuide from './en-US/workerGuide'
import workerNodes from './en-US/workerNodes'
import taskTypeConfig from './en-US/taskTypeConfig'
import settings from './en-US/settings'
import demoSimulator from './en-US/demoSimulator'
import embedConfig from './en-US/embedConfig'
import activeTasks from './en-US/activeTasks'
import nav from './en-US/nav'
import spec from './en-US/spec'
import header from './en-US/header'
import home from './en-US/home'
import appearance from './en-US/appearance'
import common from './en-US/common'
import taskListExt from './en-US/taskListExt'
import activeTasksExt from './en-US/activeTasksExt'
import taskDetailExt from './en-US/taskDetailExt'
import systemSettingsExt from './en-US/systemSettingsExt'
import workerNodesExt from './en-US/workerNodesExt'
import demoSimulatorExt from './en-US/demoSimulatorExt'
import taskTypeConfigExt from './en-US/taskTypeConfigExt'
import dashboardExt from './en-US/dashboardExt'
import clientGuideExt from './en-US/clientGuideExt'
import workerGuideExt from './en-US/workerGuideExt'

export default {
  app,
  dashboard,
  taskList,
  taskDetail,
  userGuide,
  clientGuide,
  workerGuide,
  workerNodes,
  taskTypeConfig,
  settings,
  demoSimulator,
  embedConfig,
  activeTasks,
  nav,
  spec,
  header,
  home,
  appearance,
  common,
  taskListExt,
  activeTasksExt,
  taskDetailExt,
  systemSettingsExt,
  workerNodesExt,
  demoSimulatorExt,
  taskTypeConfigExt,
  dashboardExt,
  clientGuideExt,
  workerGuideExt,
}
