// AUTO-GENERATED by scripts/split-locales.cjs — do not edit by hand.
import app from './zh-CN/app'
import dashboard from './zh-CN/dashboard'
import taskList from './zh-CN/taskList'
import taskDetail from './zh-CN/taskDetail'
import userGuide from './zh-CN/userGuide'
import clientGuide from './zh-CN/clientGuide'
import workerGuide from './zh-CN/workerGuide'
import workerNodes from './zh-CN/workerNodes'
import taskTypeConfig from './zh-CN/taskTypeConfig'
import settings from './zh-CN/settings'
import demoSimulator from './zh-CN/demoSimulator'
import embedConfig from './zh-CN/embedConfig'
import activeTasks from './zh-CN/activeTasks'
import nav from './zh-CN/nav'
import spec from './zh-CN/spec'
import header from './zh-CN/header'
import home from './zh-CN/home'
import appearance from './zh-CN/appearance'
import common from './zh-CN/common'
import taskListExt from './zh-CN/taskListExt'
import activeTasksExt from './zh-CN/activeTasksExt'
import taskDetailExt from './zh-CN/taskDetailExt'
import systemSettingsExt from './zh-CN/systemSettingsExt'
import workerNodesExt from './zh-CN/workerNodesExt'
import demoSimulatorExt from './zh-CN/demoSimulatorExt'
import taskTypeConfigExt from './zh-CN/taskTypeConfigExt'
import dashboardExt from './zh-CN/dashboardExt'
import clientGuideExt from './zh-CN/clientGuideExt'
import workerGuideExt from './zh-CN/workerGuideExt'

export default {
  app,
  dashboard,
  taskList,
  taskDetail,
  userGuide,
  clientGuide,
  workerGuide,
  workerNodes,
  taskTypeConfig,
  settings,
  demoSimulator,
  embedConfig,
  activeTasks,
  nav,
  spec,
  header,
  home,
  appearance,
  common,
  taskListExt,
  activeTasksExt,
  taskDetailExt,
  systemSettingsExt,
  workerNodesExt,
  demoSimulatorExt,
  taskTypeConfigExt,
  dashboardExt,
  clientGuideExt,
  workerGuideExt,
}
