#!/usr/bin/env node
/* eslint-disable */
// One-shot script: split src/locales/{zh-CN,en-US}.ts into per-key files.
// Run: node scripts/split-locales.cjs

const fs = require('fs')
const path = require('path')

const LOCALES_DIR = path.resolve(__dirname, '..', 'src', 'locales')

/**
 * Walk the source of an "export default { ... }" file and extract each top-level
 * key + its value subtree (as a raw string).
 */
function extractTopLevelKeys(src) {
  // Strip "export default"
  const m = src.match(/^export\s+default\s+/)
  const body = m ? src.slice(m[0].length) : src

  // Find the opening '{' of the outer object.
  const start = body.indexOf('{')
  if (start < 0) throw new Error('No opening brace')

  const entries = []
  let i = start + 1
  const n = body.length

  const skipWSandComments = (pos) => {
    while (pos < n) {
      const c = body[pos]
      if (/\s/.test(c)) { pos++; continue }
      if (c === '/' && body[pos + 1] === '/') {
        while (pos < n && body[pos] !== '\n') pos++
        continue
      }
      if (c === '/' && body[pos + 1] === '*') {
        pos += 2
        while (pos < n && !(body[pos] === '*' && body[pos + 1] === '/')) pos++
        pos += 2
        continue
      }
      break
    }
    return pos
  }

  while (i < n) {
    i = skipWSandComments(i)
    if (i >= n) break
    if (body[i] === '}') break // end of outer object

    // Read key (identifier or quoted string)
    let keyEnd
    let key
    if (body[i] === '"' || body[i] === "'" || body[i] === '`') {
      const quote = body[i]
      keyEnd = i + 1
      while (keyEnd < n && body[keyEnd] !== quote) {
        if (body[keyEnd] === '\\') keyEnd++
        keyEnd++
      }
      key = body.slice(i + 1, keyEnd)
      keyEnd++ // skip closing quote
    } else {
      keyEnd = i
      while (keyEnd < n && /[A-Za-z0-9_$]/.test(body[keyEnd])) keyEnd++
      key = body.slice(i, keyEnd)
    }

    // skip whitespace/comments
    let p = skipWSandComments(keyEnd)
    if (body[p] !== ':') {
      // not a key:value, probably a comma drift; bail
      i = p + 1
      continue
    }
    p++ // skip ':'
    p = skipWSandComments(p)

    // Now read value until matching ',' at depth 0 (relative to this value)
    const valueStart = p
    let depth = 0
    let inStr = false
    let strCh = ''
    while (p < n) {
      const c = body[p]
      if (inStr) {
        if (c === '\\') { p += 2; continue }
        if (c === strCh) inStr = false
        p++
        continue
      }
      if (c === '"' || c === "'" || c === '`') { inStr = true; strCh = c; p++; continue }
      if (c === '/' && body[p + 1] === '/') {
        while (p < n && body[p] !== '\n') p++
        continue
      }
      if (c === '/' && body[p + 1] === '*') {
        p += 2
        while (p < n && !(body[p] === '*' && body[p + 1] === '/')) p++
        p += 2
        continue
      }
      if (c === '{' || c === '[' || c === '(') { depth++; p++; continue }
      if (c === '}' || c === ']' || c === ')') { depth--; p++; continue }
      if (c === ',' && depth === 0) break
      p++
    }
    const valueEnd = p
    const value = body.slice(valueStart, valueEnd).trim().replace(/,$/, '')
    entries.push({ key, value })
    i = valueEnd
    // skip optional comma
    while (i < n && (body[i] === ',' || /\s/.test(body[i]) || body[i] === '/' )) {
      if (body[i] === '/' && body[i + 1] === '/') {
        while (i < n && body[i] !== '\n') i++
        continue
      }
      if (body[i] === '/' && body[i + 1] === '*') {
        i += 2
        while (i < n && !(body[i] === '*' && body[i + 1] === '/')) i++
        i += 2
        continue
      }
      i++
    }
  }
  return entries
}

function splitLocale(locale) {
  const srcFile = path.join(LOCALES_DIR, `${locale}.ts`)
  const outDir = path.join(LOCALES_DIR, locale)
  fs.mkdirSync(outDir, { recursive: true })

  const src = fs.readFileSync(srcFile, 'utf8')
  const entries = extractTopLevelKeys(src)

  console.log(`[${locale}] found ${entries.length} top-level keys`)

  // Detect duplicate keys (we just take the last one like JS would)
  const byKey = new Map()
  for (const e of entries) byKey.set(e.key, e)
  if (byKey.size !== entries.length) {
    console.warn(`[${locale}] WARNING: duplicate top-level keys detected, last wins`)
  }

  const importLines = []
  for (const [key, entry] of byKey) {
    const safeName = key.replace(/[^A-Za-z0-9_$]/g, '_')
    const outFile = path.join(outDir, `${safeName}.ts`)
    const fileContent = `export default ${entry.value}\n`
    fs.writeFileSync(outFile, fileContent)
    importLines.push(`import ${safeName} from './${locale}/${safeName}'`)
  }

  const aggregator = `// AUTO-GENERATED by scripts/split-locales.cjs — do not edit by hand.
${importLines.join('\n')}

export default {
${Array.from(byKey.keys()).map(k => `  ${k.replace(/[^A-Za-z0-9_$]/g, '_')},`).join('\n')}
}
`
  fs.writeFileSync(srcFile, aggregator)
  console.log(`[${locale}] wrote ${byKey.size} files + aggregator`)
}

splitLocale('zh-CN')
splitLocale('en-US')
console.log('Done.')
